# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
# url: http://username.github.io/
# baseurl: /sustain/
title: Marina Torres Trimallez
author: Marina Torres Trimallez
description: Personal page and resume
avatar: https://www.xing.com/image/2_8_0_962412c3a_30522263_1/alma-eguizabal-foto.1024x1024.jpg
email: alma.eguizabal@ieee.org
github: jekyller/sustain # username
twitter: username
linkedin: username
stackoverflow: username   #e.g: users/2735833/proton1h1
google-scholar: google-scholar
researchgate: Alma_Eguizabal
#Comment out if you don't want disqus
# disqus: username
google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]

# trying to add the new icons...
social:
- {icon: 'researchgate', link: 'https://www.researchgate.net/profile/profileName'}
- {icon: 'google-scholar', link: 'https://scholar.google.com/citations?user=userID'}
